-- Ejecutar en Supabase SQL Editor
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS metodo_pago VARCHAR(20) NOT NULL DEFAULT 'MERCADOPAGO';
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS webpay_token VARCHAR(255);
ALTER TABLE pagos ADD COLUMN IF NOT EXISTS webpay_tbk_id VARCHAR(255);
