"""unique_mp_payment_id

Revision ID: 14d36c2118e5
Revises: 9fc01dccf066
Create Date: 2026-06-18 21:14:09.445218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '14d36c2118e5'
down_revision: Union[str, Sequence[str], None] = '9fc01dccf066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pagos', ['mp_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagos', type_='unique')
    # ### end Alembic commands ###
