"""init

Revision ID: 182533923411
Revises: 
Create Date: 2026-06-15 01:37:26.575418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '182533923411'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_parent_id'), 'categorias', ['parent_id'], unique=False)
    op.create_index(op.f('ix_categorias_slug'), 'categorias', ['slug'], unique=True)
    op.create_table('planes',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('precio_anual', sa.Float(), nullable=False),
    sa.Column('features', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.Enum('CLIENTE', 'PROVEEDOR', 'ADMIN', name='rol_usuario'), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verificado', sa.Boolean(), nullable=False),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('servicios',
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio_min', sa.Float(), nullable=True),
    sa.Column('precio_max', sa.Float(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('radio_cobertura_km', sa.Integer(), nullable=False),
    sa.Column('direccion_texto', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'PAUSADO', 'ELIMINADO', name='estado_servicio'), nullable=False),
    sa.Column('fotos', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicios_categoria_id'), 'servicios', ['categoria_id'], unique=False)
    op.create_index(op.f('ix_servicios_proveedor_id'), 'servicios', ['proveedor_id'], unique=False)
    op.create_table('suscripciones',
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVA', 'CANCELADA', 'EXPIRADA', 'PENDIENTE', name='estado_suscripcion'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_proveedor_id'), 'suscripciones', ['proveedor_id'], unique=False)
    op.create_table('contrataciones',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('servicio_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'ACEPTADO', 'RECHAZADO', 'EN_PROGRESO', 'COMPLETADO', 'CANCELADO', 'PAGADO_GARANTIA', name='estado_contratacion'), nullable=False),
    sa.Column('monto_acordado', sa.Float(), nullable=True),
    sa.Column('mensaje_solicitud', sa.Text(), nullable=True),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrataciones_cliente_id'), 'contrataciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_contrataciones_proveedor_id'), 'contrataciones', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_contrataciones_servicio_id'), 'contrataciones', ['servicio_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('contratacion_id', sa.UUID(), nullable=False),
    sa.Column('emisor_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones.id'], ),
    sa.ForeignKeyConstraint(['emisor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_contratacion_id'), 'mensajes', ['contratacion_id'], unique=False)
    op.create_index(op.f('ix_mensajes_emisor_id'), 'mensajes', ['emisor_id'], unique=False)
    op.create_table('pagos',
    sa.Column('contratacion_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fee_plataforma', sa.Float(), nullable=False),
    sa.Column('monto_neto', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', 'LIBERADO', 'REEMBOLSADO', name='estado_pago'), nullable=False),
    sa.Column('gateway', sa.String(length=50), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_preference_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_contratacion_id'), 'pagos', ['contratacion_id'], unique=True)
    op.create_table('resenas',
    sa.Column('contratacion_id', sa.UUID(), nullable=False),
    sa.Column('calificador_id', sa.UUID(), nullable=False),
    sa.Column('calificado_id', sa.UUID(), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calificado_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['calificador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacion_id')
    )
    op.create_index(op.f('ix_resenas_calificado_id'), 'resenas', ['calificado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resenas_calificado_id'), table_name='resenas')
    op.drop_table('resenas')
    op.drop_index(op.f('ix_pagos_contratacion_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_mensajes_emisor_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_contratacion_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_contrataciones_servicio_id'), table_name='contrataciones')
    op.drop_index(op.f('ix_contrataciones_proveedor_id'), table_name='contrataciones')
    op.drop_index(op.f('ix_contrataciones_cliente_id'), table_name='contrataciones')
    op.drop_table('contrataciones')
    op.drop_index(op.f('ix_suscripciones_proveedor_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_servicios_proveedor_id'), table_name='servicios')
    op.drop_index(op.f('ix_servicios_categoria_id'), table_name='servicios')
    op.drop_table('servicios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('planes')
    op.drop_index(op.f('ix_categorias_slug'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_parent_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
