"""solicitudes_propuestas

Revision ID: 9fc01dccf066
Revises: d4e5f6a7b8c9
Create Date: 2026-06-18 00:42:18.933665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9fc01dccf066'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes',
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('presupuesto_max', sa.Float(), nullable=True),
    sa.Column('ubicacion_texto', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ABIERTA', 'CERRADA', name='status_solicitud'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_cliente_id'), 'solicitudes', ['cliente_id'], unique=False)
    op.create_table('propuestas',
    sa.Column('solicitud_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('tiempo_estimado', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDIENTE', 'ACEPTADA', 'RECHAZADA', 'CANCELADA', name='status_propuesta'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propuestas_proveedor_id'), 'propuestas', ['proveedor_id'], unique=False)
    op.create_index(op.f('ix_propuestas_solicitud_id'), 'propuestas', ['solicitud_id'], unique=False)
    op.add_column('contrataciones', sa.Column('propuesta_id', sa.UUID(), nullable=True))
    op.alter_column('contrataciones', 'servicio_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'contrataciones', 'propuestas', ['propuesta_id'], ['id'])
    op.drop_index(op.f('idx_usuarios_ubicacion'), table_name='usuarios', postgresql_using='gist')
    op.create_index(op.f('ix_usuarios_codigo_referido'), 'usuarios', ['codigo_referido'], unique=True)
    op.drop_column('usuarios', 'ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuarios_codigo_referido'), table_name='usuarios')
    op.create_index(op.f('idx_usuarios_ubicacion'), 'usuarios', ['ubicacion'], unique=False, postgresql_using='gist')
    op.drop_constraint(None, 'contrataciones', type_='foreignkey')
    op.alter_column('contrataciones', 'servicio_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('contrataciones', 'propuesta_id')
    op.drop_index(op.f('ix_propuestas_solicitud_id'), table_name='propuestas')
    op.drop_index(op.f('ix_propuestas_proveedor_id'), table_name='propuestas')
    op.drop_table('propuestas')
    op.drop_index(op.f('ix_solicitudes_cliente_id'), table_name='solicitudes')
    op.drop_table('solicitudes')
    # ### end Alembic commands ###
