"""disputas_y_referidos

Revision ID: e672bf5cf4af
Revises: 182533923411
Create Date: 2026-06-15 02:02:25.737101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'e672bf5cf4af'
down_revision: Union[str, Sequence[str], None] = '182533923411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputas',
    sa.Column('contratacion_id', sa.UUID(), nullable=False),
    sa.Column('abridor_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('evidencias', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ABIERTA', 'EN_REVISION', 'RESUELTA', name='estado_disputa'), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abridor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['contratacion_id'], ['contrataciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contratacion_id')
    )
    op.add_column('usuarios', sa.Column('codigo_referido', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('referido_por', sa.UUID(), nullable=True))
    op.add_column('usuarios', sa.Column('referidos_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_usuarios_codigo_referido'), 'usuarios', ['codigo_referido'], unique=True)
    op.create_foreign_key(None, 'usuarios', 'usuarios', ['referido_por'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_codigo_referido'), table_name='usuarios')
    op.drop_column('usuarios', 'referidos_count')
    op.drop_column('usuarios', 'referido_por')
    op.drop_column('usuarios', 'codigo_referido')
    op.drop_table('disputas')
    # ### end Alembic commands ###
